/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package csci2320;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.Scanner;

public class App {
    static record IndexValuePair(int index, int value) {}

    public static void main(String[] args) {
        try (Scanner sc = new Scanner(System.in)) {
            Random rand = new Random(sc.nextLong());
            int size = sc.nextInt();
            String testType = sc.next();
            switch (testType) {
                case "get":
                    testGet(size, rand);
                    break;
                case "set":
                    testSet(size, rand);
                    break;
                case "immutable":
                    testImmutable(size, rand);
                    break;
            }
        }
    }

    static void printSeqSums(BTVector<Integer> seq) {
        int sum = 0;
        for (int i: seq) sum += i;
        System.out.println(sum);
    }

    static void testGet(int size, Random rand) {
        BTVector<Integer> vec = BTVector.empty();
        List<Integer> nums = new ArrayList<>();
        for (int i = 0; i < size; ++i) {
            var n = rand.nextInt();
            vec = vec.add(n);
            nums.add(n);
        }
        for (int i = 0; i < size; ++i) {
            if (!nums.get(i).equals(vec.get(i))) {
                System.out.println("get failed " + i + ", " + nums.get(i) + " != " + vec.get(i));
                return;
            }
        }
        printSeqSums(vec);
    }

    static void testSet(int size, Random rand) {
        BTVector<Integer> vec = BTVector.empty();
        List<Integer> nums = new ArrayList<>();
        for (int i = 0; i < size; ++i) {
            var n = rand.nextInt();
            vec = vec.add(n);
            nums.add(n);
        }
        printSeqSums(vec);
        List<IndexValuePair> ivps = new ArrayList<>();
        for (int i = 0; i < size; ++i) {
            if (rand.nextDouble() < 0.3) {
                var n = rand.nextInt();
                vec = vec.set(i, n);
                ivps.add(new IndexValuePair(i, n));
            }
        }
        for (var ivp : ivps) {
            if (!vec.get(ivp.index).equals(ivp.value)) {
                System.out.println("get failed " + ivp + ", " + vec.get(ivp.index));
                return;
            }
        }
        printSeqSums(vec);
    }

    static void testImmutable(int size, Random rand) {
        List<Double> nums = new ArrayList<>();
        List<BTVector<Double>> vecs = new ArrayList<>();
        for (int i = 0; i < size; ++i) {
            double x = rand.nextDouble();
            nums.add(x);
            if (i == 0) {
                vecs.add(BTVector.<Double>empty().add(x));
            } else {
                vecs.add(vecs.get(i-1).add(x));
            }
        }
        for (int i = 0; i < size; ++i) {
            var v = vecs.get(i);
            if (i+1 != v.size()) {
                System.out.println("Vector " + i + " is wrong size: " + vecs.get(i).size());
                return;
            }
            for (int j = 0; j <= i; ++j) {
                if (!v.get(j).equals(nums.get(j))) {
                    System.out.println("Wrong value in vector " + i + " at " + j);
                }
            }
        }
        double sum = 0.0;
        for (var x : vecs.get(size - 1)) sum += x;
        System.out.printf("Sum: %1.4f", sum);
    }
}
